Online_CV/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from dashboard import views as dashview
from . import views
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.homepage),
    path('', dashview.dashboard_view),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('accountss/', include('allauth.urls')),
    path('createpages/', include('createpage.urls')),

    path('', include('django.contrib.auth.urls'))

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('logout', views.logout_views, name='logout'),
    path('login', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),

    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(), name="reset_password_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="reset_password_complete"),

]

createpage/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls import url
from django.urls import path


app_name = 'pages'

urlpatterns = [
  path('Resumes', views.createpage, name='createpage'),

]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls import url
from django.urls import path


app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_view, name='dashboard_view'),
    path('form/', views.newProfile, name='profile_form'),
    path('updateinfo/', views.update_profile, name='updateinfo'),
    path('CV/<id>/', views.generate, name='generate'),
    path('addCvDetails', views.addcvdetail, name='updateform1'),
    path('addCVDetails2', views.addcvdetail2, name='resumeform2'),
    path('generatecv', views.generateCV, name='generatecv'),
    path('selectcv', views.selectcv, name='selectcv'),
    path('addEmployeepic', views.addpic, name='employeepic'),
    path('printcv/<id>', views.printcv, name='printcv'),
    path('printblackcv/<id>', views.printcvblack, name='printblackcv'),
    path('generateblackcv/<id>', views.generateCV2, name='generateblackcv')

]

createpage/models.py
from django.db import models

# Create your models here.

createpage/views.py
from django.shortcuts import render

# Create your views here.
from dashboard.models import Profile, CV, CV2


def createpage(request):
    cv = CV.objects.filter(user=request.user).all()
    cv2 = CV2.objects.filter(user=request.user).all()
    print(cv)
    return render(request, 'createpage/addpages.html', {'cv': cv, 'cv2' : cv2})

createpage/templates/createpage/addpages.html
{% extends 'basetemplate.html' %}
{% load static %}

{%block content  %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4" xmlns="http://www.w3.org/1999/html">
        <div class="row">
         <div class="col-lg-2">
                <div class="card" style="width: 10rem; border-color: white">
                    <a href="{% url 'dashboard:selectcv' %}">  <img  class="card-img-top" src="{% static 'newplus.jpeg' %}" alt="Card image cap">
                </div>
            </div>

            {% for cv in cv %}

                <div class="col-lg-2" >
                    <div class="card " style="width: 10rem;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
;">

                        <a  href="{% url 'dashboard:generate' cv.id %}" ><img style="height: 158px; width: 158px" class="card-img-top" src="{% static 'bluecv2.jpg' %}" alt="Card image cap"></a>

                        <div class="card-body " style="text-align: center;">
                            {% for title in cv.title.all %}
                                <a style=" color: black; " href="{% url 'dashboard:generate' cv.id %}" >  <h7 class="card-title">{{ title.resumetitle}}</h7></a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>
    <br>

            <div class="row">

            {% for cv2 in cv2 %}

                <div class="col-lg-2" >
                    <div class="card " style="width: 10rem;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
;">

                        <a  href="{% url 'dashboard:generateblackcv' cv2.id %}" ><img style="height: 158px; width: 158px" class="card-img-top" src="{% static 'Capture.jpg' %}" alt="Card image cap"></a>

                        <div class="card-body " style="text-align: center;">
                            {% for title in cv2.titlecv2.all %}
                                <a style=" color: black; " href="{% url 'dashboard:generateblackcv' cv2.id %}" >  <h7 class="card-title">{{ title.titcv2}}</h7></a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}




        </div>



    </main>

{% endblock %}