Online_CV/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from dashboard import views as dashview
from . import views
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.homepage),
    path('', dashview.dashboard_view),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('accountss/', include('allauth.urls')),
    path('createpages/', include('createpage.urls')),

    path('', include('django.contrib.auth.urls'))

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('logout', views.logout_views, name='logout'),
    path('login', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),

    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(), name="reset_password_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="reset_password_complete"),

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForms(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

accounts/views.py
from  django.contrib.auth import logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
# from FYP_ERM.decorators import unauthenticated_user
from django.contrib.auth.forms import UserCreationForm

from dashboard.models import Profile, ProfileSkills
from .forms import CreateUserForms
from django.contrib import messages
from django.contrib.auth.models import Group
from django.http import HttpResponse





# Create your views here.
def logout_views(request):
    if request.method == 'POST':
        logout(request)
        # return redirect('dashboard:dashboard_view')
        return login_view(request)

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('dashboard:dashboard_view')
            # return HttpResponse("yes")
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/newlogin.html', {'form': form})

def register_view(request):
    form = CreateUserForms()

    if request.method == 'POST':
        form = CreateUserForms(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='client')
            user.groups.add(group)

            messages.info(request, 'Account was Successfully created for ' + username)
            return redirect('accounts:login')

    context = {'form':form}
    return render(request,'accounts/register.html',context)

accounts/templates/accounts/newlogin.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body{
            background-color: white;
        }
        .user_card {

            height: 450px;
            width: 500px;
            margin-top: auto;
            margin-bottom: auto;
            background: white;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
        {#box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
            border-radius: 15px;
            margin-right: 220px;

        }

        .form_container {
            margin-top: 20px;
        }
        .form-control {
            display: block;
            width: 100%;
            height: calc(2.25rem + 2px);
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: .25rem;
            transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
        }

        #form-title{
            color: black;

        }

        .login_btn {
            margin-bottom: 10px;
            width: 100%;
            background: #10717F !important;
            color: black !important;
        }
        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
        .login_container {
            padding: 0 2rem;
        }
        .input-group-text {
            background: #10717F !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }
        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        {##messages{#}
        {#    background-color: grey;#}
        {#    color: #fff;#}
        {#    padding: 10px;#}
        {#    margin-top: 10px;#}
        {#}#}
        .h-100 {
            width: 100%;
            padding-right: 15px;
            padding-left: 15px;

            margin-left: auto;
        }

    </style>

</head>
<body>


<div class="container-fluid" style=" width: 100%; padding-right: 15px; padding-left: 0px">
    <div class="row">
        <div class="col-4">
            <img src="{% static 'left.png' %}" style="width: 500px;height: 625px;">

        </div>

        <div class="col-8">


            <div class="d-flex justify-content-end h-100">
                <div class="user_card">
                    <div class="d-flex justify-content-center">


                        <h1 id="form-title" style="color: #10717F">Welcome to CV Builder</h1>

                    </div>
                    <div class="d-flex justify-content-center form_container">
                        <form method="POST" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                <input type="text" name="username" placeholder="Username..." class="form-control">
                            </div>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                <input type="password" name="password" placeholder="Password..." class="form-control" >
                            </div>

                            <div class="d-flex justify-content-center mt-3 " >
                                <button class="btn login_btn" type="submit"><h5 style="color: white">Login</h5></button>
                                {#                                <input class="btn login_btn"  type="submit" value="Login">#}

                            </div>
                            <button class="btn btn-light pl-5 pr-5"  style=""><img  style="height: 20px; width:20px; margin-right: 20px" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg" > <a href="{% provider_login_url "google" %}">Sign in with Google</a></button>



                        </form>
                    </div>
                    <div class="mt-4">
                        <div class="d-flex justify-content-center links" style="color: black">
                            Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2" style="color: black">Sign Up</a>
                        </div>

                        <div class="msg" style="margin-left: 80px;margin-top: 20px">
                            {% if messages %}
                                {% for message in messages %}
                                    <p id="messages">{{message}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</div>
</body>


</html>

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
        {#background: #10717F;#}
        {#background: url("{% static 'pic232.jpg' %}")  ;#}
        {#background-repeat: no-repeat;#}

        {#background: url("{% static 'pic1.jpg' %}") !important;#}
        }
        .user_card {

            height: 450px;
            width: 500px;
            margin-top: auto;
            margin-bottom: auto;
            background: white;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
        {#box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
            border-radius: 15px;
            margin-right: 220px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title{
            color: black;
        }
        .login_btn {
            width: 100%;
            background: #10717F !important;
            color: white !important;
        }
        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
        .login_container {
            padding: 0 2rem;
        }
        .input-group-text {
            background: #10717F !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }
        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }


    </style>

</head>
<body>

<div class="container-fluid" style=" width: 100%; padding-right: 15px; padding-left: 0px">
    <div class="row">
        <div class="col-4">
            <img src="{% static 'left.png' %}" style="width: 500px;height: 625px;">

        </div>

        <div class="col-8">
            <div class="container h-100">
                <div class="d-flex justify-content-end h-100">
                    <div class="user_card">
                        <div class="d-flex justify-content-center">
                            <h1 id="form-title" style="color: #10717F">Welcome to CV Builder</h1>
                        </div>
                        <div class="d-flex justify-content-center form_container">

                            <form method="POST" action="">
                                {% csrf_token %}

                                <div class="input-group mb-3">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                    </div>
                                    {{ form.username }}
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                                    </div>
                                    {{ form.email }}
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                    </div>
                                    {{ form.password1 }}
                                </div>
                                <div class="input-group mb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                    </div>
                                    {{ form.password2 }}
                                </div>

                                <div class="d-flex justify-content-center mt-3 ">
                                    <input class="btn login_btn" type="submit" value="Register Account">
                                </div>
                            </form>
                        </div>


                        <div class="eroor" style="margin-left: 35px">
                            {{ form.errors  }}
                        </div>

                        <div class="mt-4">
                            <div class="d-flex justify-content-center links">
                                Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='Username..';
        form_fields[2].placeholder='Email..';
        form_fields[3].placeholder='Enter password...';
        form_fields[4].placeholder='Re-enter Password...';


        for (var field in form_fields){
            form_fields[field].className += ' form-control'
        }
    </script>
</div>
</body>
</html>
{##}
{#        <h1>Registeras</h1>#}
{#        <form method="POST" action="">#}
{#            {% csrf_token %}#}
{#            {{ form.username.label   }}#}
{#            {{ form.username }}#}
{##}
{#            {{ form.email.label }}#}
{#            {{ form.email }}#}
{##}
{#            {{ form.password1.label }}#}
{#            {{ form.password1 }}#}
{##}
{#            {{ form.password2.label }}#}
{#            {{ form.password2 }}#}
{##}
{#            {% for field in form %}#}
{#                {{ field.label }}#}
{#                {{ field }}#}
{#             {% endfor %}#}
{#      {{ form.as_p }}#}
{#            <input type="submit" name="Create User">#}
{##}
{#        </form>#}