Online_CV/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from dashboard import views as dashview
from . import views
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.homepage),
    path('', dashview.dashboard_view),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('accountss/', include('allauth.urls')),
    path('createpages/', include('createpage.urls')),

    path('', include('django.contrib.auth.urls'))

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('logout', views.logout_views, name='logout'),
    path('login', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),

    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(), name="reset_password_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="reset_password_complete"),

]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls import url
from django.urls import path


app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_view, name='dashboard_view'),
    path('form/', views.newProfile, name='profile_form'),
    path('updateinfo/', views.update_profile, name='updateinfo'),
    path('CV/<id>/', views.generate, name='generate'),
    path('addCvDetails', views.addcvdetail, name='updateform1'),
    path('addCVDetails2', views.addcvdetail2, name='resumeform2'),
    path('generatecv', views.generateCV, name='generatecv'),
    path('selectcv', views.selectcv, name='selectcv'),
    path('addEmployeepic', views.addpic, name='employeepic'),
    path('printcv/<id>', views.printcv, name='printcv'),
    path('printblackcv/<id>', views.printcvblack, name='printblackcv'),
    path('generateblackcv/<id>', views.generateCV2, name='generateblackcv')

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profilepic(models.Model):
    picture = models.ImageField(blank=True)


class ProfileCertificate(models.Model):
    cert = models.TextField(blank=True, max_length=50)


class ProfileProession(models.Model):
    profession = models.TextField(blank=True, max_length=50)


class ProfessionalEducation(models.Model):
    profedu = models.TextField(blank=True, max_length=300)


class Profileinfo(models.Model):
    info = models.TextField(blank=True, max_length=600)


class Recommendations(models.Model):
    recomend = models.TextField(blank=True, max_length=300)
    recomendby = models.TextField(blank=True, max_length=500)


class cvtitle(models.Model):
    resumetitle = models.TextField(blank=True, max_length=300)





class ProfileEducation(models.Model):
    institute = models.TextField(max_length=50)
    board = models.TextField(max_length=50)
    degree = models.TextField(max_length=50)
    startingdate = models.TextField(max_length=20)
    endingdate = models.TextField(max_length=20)
    result = models.TextField(max_length=10)
    percentage = models.IntegerField(default=None)

    def __str__(self):
        return self.institute


class ProfileSkills(models.Model):
    skills = models.TextField(max_length=20)

    def __str__(self):
        return self.skills


class ProfileExperience(models.Model):
    organization = models.TextField(max_length=20)
    previousDesignation = models.TextField(max_length=20)
    startingDate = models.TextField(max_length=20)
    endingDate = models.TextField(max_length=20)
    responsibilities = models.TextField(max_length=100)

    # abc = models.

    def __str__(self):
        return self.organization


class Profile(models.Model):
    boolChoice = (
        ("Male", "Male"), ("Female", "Female"))

    name = models.CharField(max_length=50)
    fname = models.TextField(max_length=50)
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices=boolChoice)
    profile_pic = models.ImageField(default='place.png')

    email = models.TextField(max_length=20, default=None)
    contactno1 = models.IntegerField(default=None)
    contactno2 = models.IntegerField(blank=True, null=True)
    linkedin = models.TextField(max_length=50, default=None)
    address = models.TextField(max_length=100, default=None)

    education = models.ManyToManyField(ProfileEducation, default=None)
    experience = models.ManyToManyField(ProfileExperience, default=None)
    skills = models.ManyToManyField(ProfileSkills, default=None)
    # contact = models.ManyToManyField(ProfileContact, default=None)

    user = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name


class CV(models.Model):
    certificate = models.ManyToManyField(ProfileCertificate, default=None)
    profession = models.ManyToManyField(ProfileProession, default=None)
    profinfo = models.ManyToManyField(Profileinfo, default=None)
    recommend = models.ManyToManyField(Recommendations, default=None)
    title = models.ManyToManyField(cvtitle, default=None)

    user = models.ManyToManyField(User, blank=True)


class checks(models.Model):
    boolean = models.BooleanField()
    user = models.ManyToManyField(User, blank=True)


class ProfileProfessioncv2(models.Model):
    procv2 = models.TextField(blank=True, max_length=300)

class ProfileIntroductioncv2(models.Model):
    introcv2 = models.TextField(blank=True, max_length=300)

class ProfileAreaofexpertisecv2(models.Model):
    areaofexpertisecv2 = models.TextField(blank=True, max_length=300)

class ProfileBooksAuthoredcv2(models.Model):
    bookscv2 = models.TextField(blank=True, max_length=300)

class ProfileCertificatecv2(models.Model):
    certcv2 = models.TextField(blank=True, max_length=300)

class ProfileReferencescv2(models.Model):
    refcv2 = models.TextField(blank=True, max_length=300)
    orgcv2 = models.TextField(blank=True, max_length=300)
    emailcv2 = models.TextField(blank=True, max_length=300)


class ProfileAwardscv2(models.Model):
    awcv2 = models.TextField(blank=True, max_length=300)

class ProfileTitlecv2(models.Model):
    titcv2 = models.TextField(blank=True, max_length=300)


class CV2(models.Model):
    professsioncv2 = models.ManyToManyField(ProfileProfessioncv2,default=None)
    introductioncv2 = models.ManyToManyField(ProfileIntroductioncv2,default=None)
    area_of_expertisecv2 = models.ManyToManyField(ProfileAreaofexpertisecv2,default=None)
    books_authored = models.ManyToManyField(ProfileBooksAuthoredcv2,default=None)
    certificatecv2 = models.ManyToManyField(ProfileCertificatecv2,default=None)
    referencescv2 = models.ManyToManyField(ProfileReferencescv2,default=None)
    awardscv2 = models.ManyToManyField(ProfileAwardscv2,default=None)
    titlecv2 = models.ManyToManyField(ProfileTitlecv2, default=None)

    user = models.ManyToManyField(User,blank=True)

dashboard/forms.py
from django import forms
from . import models


class addProfilepic(forms.ModelForm):
    class Meta:
        model = models.Profilepic
        fields = {'picture'}

    def __init__(self, *args, **kwargs):
        super(addProfilepic, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

dashboard/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from createpage import urls as createurl

# Create your views here.
from . import forms
from dashboard.models import Profile, ProfileEducation, ProfileExperience, ProfileSkills, ProfileProession, \
    ProfileCertificate, ProfessionalEducation, Profileinfo, Profilepic, Recommendations, CV, cvtitle, checks, CV2, \
    ProfileProfessioncv2, ProfileIntroductioncv2, ProfileAreaofexpertisecv2, ProfileCertificatecv2, \
    ProfileReferencescv2, ProfileAwardscv2, ProfileTitlecv2, ProfileBooksAuthoredcv2


def addpic(request):
    if request.method == 'POST':
        form = forms.addProfilepic(request.POST, request.FILES)
        if form.is_valid():
            obj = Profile.objects.get(user=request.user)
            r = form.save()
            print("---------- 1st")
            print(request.FILES['picture'].name)
            obj.profile_pic = request.FILES['picture'].name

            print("----------")
            obj.save()
            request.method='GET'
            return newProfile(request)
    else:
        form = forms.addProfilepic()
    return newProfile(request)


@login_required(login_url='/accounts/login')
def dashboard_view(request):
    return newProfile(request)


def profile_form(request):
    id = request.user.id
    detail = Profile.objects.filter(id=id)
    return render(request, 'dashboard/profile_view.html', {'id': id, 'detail': detail})


def newProfile(request):
    id = request.user.id
    if request.method == 'POST':
        form = forms.addProfilepic(request.POST, request.FILES)
        if form.is_valid():
            obj = Profile.objects.filter(user=request.user).first()
            r = form.save()
            print("---------- 1st")

            # obj.profile_pic = request.FILES['picture'].name

            print("----------")
            obj.save()
            return newProfile(request)
    else:
        form = forms.addProfilepic()
    detail = Profile.objects.filter(user=request.user).first()
    return render(request, 'dashboard/profile_view.html', {'id': id, 'form': form, 'detail': detail})


def update_profile(request):
    id = request.user.id
    profile = Profile.objects.filter(user=request.user).first()
    print(profile)

    if request.method == 'POST':
        if profile:
            print("--------------")
        else:
            profile = Profile()
        firstname = request.POST.get("fname")
        fathername = request.POST.get("lname")
        aging = request.POST.get("age")
        sex = request.POST.get("gender")

        # education

        inslist = request.POST.getlist("Institute[]")
        boardlist = request.POST.getlist("Board_Uni[]")
        degreelist = request.POST.getlist("Degree[]")
        startingdatelist = request.POST.getlist("PassingYear[]")
        endingdatelist = request.POST.getlist("enddate[]")
        resultlist = request.POST.getlist("Result[]")
        percentagelist = request.POST.getlist("Number_CGPA[]")

        # Experience

        orglist = request.POST.getlist("Organization[]")
        pdlist = request.POST.getlist("Previous_Designation[]")
        fromdlist = request.POST.getlist("FromDate[]")
        todlist = request.POST.getlist("ToDate[]")
        reslist = request.POST.getlist("Responsibility[]")

        # skiils
        skilllist = request.POST.getlist('Skills[]')

        # contact
        mail = request.POST.get('email')
        number1 = request.POST.get('contact1')
        number2 = request.POST.get('contact2')
        linked = request.POST.get('linkedin')
        location = request.POST.get('address')

        profile.name = firstname
        profile.fname = fathername
        profile.age = aging
        profile.gender = sex

        profile.email = mail
        profile.contactno1 = number1
        profile.contactno2 = number2
        profile.linkedin = linked
        profile.address = location
        profile.save()
        profile.user.add(request.user)
        profile.save()

        # cont = ProfileContact(email=mail, contactno1=number1, contactno2=number2, linkedin=linked, address=location)
        # cont.save()
        # profile.contact.add(cont)
        # profile.save()

        profile.education.clear()
        # object = Employee.objects.all()
        for i in range(len(inslist)):
            print(i)

            edu = ProfileEducation(institute=inslist[i], board=boardlist[i], degree=degreelist[i],
                                   startingdate=startingdatelist[i], endingdate=endingdatelist[i],
                                   result=resultlist[i], percentage=percentagelist[i])
            edu.save()
            profile.education.add(edu)
            profile.save()

        profile.experience.clear()
        for i in range(len(orglist)):
            exp = ProfileExperience(organization=orglist[i], previousDesignation=pdlist[i], startingDate=fromdlist[i],
                                    endingDate=todlist[i], responsibilities=reslist[i])
            exp.save()
            profile.experience.add(exp)
            profile.save()

        profile.skills.clear()
        for i in range(len(skilllist)):
            skl = ProfileSkills(skills=skilllist[i])
            skl.save()
            profile.skills.add(skl)
            profile.save()
        #
        # detail = Profile.objects.filter(user=request.user).first()
        # return render(request, 'dashboard/profile_view.html', {'id': id, 'detail': detail})
        request.method = 'GET'
        return newProfile(request)
    return render(request, 'dashboard/profile_update.html', {'profile': profile, 'id': id})


def generate(request, id):
    uid = request.user.id
    detail = Profile.objects.filter(user=request.user).first()
    cv = CV.objects.get(id=id, user=request.user)
    print(cv)
    return render(request, 'dashboard/createresume.html', {'detail': detail, 'id': uid, 'cv': cv})


def generateCV2(request, id):
    uid = request.user.id
    detail = Profile.objects.filter(user=request.user).first()
    cv2 = CV2.objects.get(id=id, user=request.user)
    print(cv2)
    return render(request, 'dashboard/cvblack.html', {'detail': detail, 'id': uid, 'cv': cv2})


def generateCV(request):
    uid = request.user.id
    detail = Profile.objects.filter(user=request.user).first()
    return render(request, 'dashboard/newresume.html', {'detail': detail, 'id': uid})

# Create PagesResume

def addcvdetail(request):
    id = request.user.id
    profile = None

    if request.method == 'POST':
        if profile:
            print("--------------")
        else:
            profile = Profile()
        cv = CV()
        cv.save()
        objectivelist = request.POST.getlist('objective[]')
        certilist = request.POST.getlist('certificate[]')
        recommendationlist = request.POST.getlist('rec[]')
        recomendbylist = request.POST.getlist('recby[]')
        titlelist = request.POST.getlist('title[]')
        professionlist = request.POST.getlist('prof[]')

        print("_________________________________")
        print(certilist)
        for i in range(len(certilist)):
            print(i)
            cer = ProfileCertificate(cert=certilist[i])
            cer.save()
            cv.certificate.add(cer)
            cv.save()

        for i in range(len(titlelist)):
            title = cvtitle(resumetitle=titlelist[i])
            title.save()
            cv.title.add(title)
            cv.save()

        for i in range(len(professionlist)):
            profe = ProfileProession(profession=professionlist[i])
            profe.save()
            cv.profession.add(profe)
            cv.save()

        for i in range(len(objectivelist)):
            objective = Profileinfo(info=objectivelist[i])
            objective.save()
            cv.profinfo.add(objective)
            cv.save()
        for i in range(len(recommendationlist)):
            recomend = Recommendations(recomend=recommendationlist[i], recomendby=recomendbylist[i])
            recomend.save()
            cv.recommend.add(recomend)
            cv.save()

        cv.user.add(request.user)

        cv.save()
        return generate(request,cv.id)
    return render(request, 'dashboard/resume_form.html', {'profile': profile, 'id': id})

def selectcv(request):
    profile = Profile.objects.filter(user=request.user).count()

    return render(request, 'dashboard/selectCV.html',{'flag':profile})

def printcv(request, id):
    uid = request.user.id
    detail = Profile.objects.filter(user=request.user).first()
    cv = CV.objects.get(id=id, user=request.user)
    print(cv)
    return render(request, 'dashboard/CVwithPrint.html', {'detail': detail, 'id': uid, 'cv': cv})

def addcvdetail2(request):
    id = request.user.id
    profile = None

    if request.method == 'POST':
        if profile:
            print("--------------")
        else:
            profile = Profile()
        cv2 = CV2()
        cv2.save()
        title2list = request.POST.getlist('titelecv2[]')
        proslist = request.POST.getlist('profession[]')
        introlist = request.POST.getlist('Introduction[]')
        expertiselist = request.POST.getlist('Areaofexpertise[]')
        bookslist = request.POST.getlist('BooksAuthored[]')
        certificatelist = request.POST.getlist('certificatecv2[]')
        reflist = request.POST.getlist('ref[]')
        orglist = request.POST.getlist('org[]')
        emaillist = request.POST.getlist('email[]')
        awardlist = request.POST.getlist('awards[]')

        print("_________________________________")

        for i in range(len(title2list)):
            print(i)
            title2 = ProfileTitlecv2(titcv2=title2list[i])
            title2.save()
            cv2.titlecv2.add(title2)
            cv2.save()


        for i in range(len(awardlist)):
            print(i)
            award2 = ProfileAwardscv2(awcv2=awardlist[i])
            award2.save()

dashboard/templates/dashboard/cvblack.html
{% extends 'basetemplate.html' %}
{% load static %}
{%block content  %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <a  href="{% url 'dashboard:printblackcv' cv.id %}"  target="_blank" class="btn btn-sm btn-outline-secondary"><i class="fas fa-print"></i> Print CV</a>
        <div><br></div>
        <div class="container-fluid" style="height: 100%">
            <div class="row" style="background-color: black; color: white ; padding-top: 20px ; height: 300px ; background-image: url({% static 'woodhr.jpg' %})">
                <div style="margin-left: 30px; margin-bottom: 30px; margin-top: 40px">
                    <h1>{{ detail.name }}</h1> <br>
                    {% for pro in cv.professsioncv2.all %}
                        <h1>{{ pro.procv2 }}</h1>
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="col-4" style="color: white; padding-top: 30px;min-height: 1000px; background-image: url({% static 'wood.jpg' %});">
                    <div style="margin-left: 30px; margin-bottom: 30px">
                        <h4 style="color:  #38b6ff"> Areas of Expertise </h4>
                        {% for aox in cv.area_of_expertisecv2.all %}
                            <p>{{ aox.areaofexpertisecv2 }}</p>
                        {% endfor %}
                    </div>
                    <div style="margin-left: 30px; margin-bottom: 30px">
                        <h4 style="color:  #38b6ff"> Books Authored </h4>
                        {% for boa in cv.books_authored.all %}
                            <p>{{ boa.bookscv2 }}</p>
                        {% endfor %}
                    </div>

                    <div style="margin-left: 30px; margin-bottom: 30px">
                        <h4 style="color:  #38b6ff"> Refferences </h4>
                        {% for ref in cv.referencescv2.all %}
                            <h6>{{ ref.refcv2 }}</h6>
                            <h6>{{ref.orgcv2 }}</h6>
                            <h6>{{ref.emailcv2 }}</h6>
                        {% endfor %}
                    </div>
                    {#Confu....#}
                    <div style="margin-left: 30px; margin-bottom: 30px">
                        <h4 style="color:  #38b6ff"> Contact </h4>
                        <h7>{{ detail.email }}</h7>
                        <h6></h6>
                        <h6>{{ detail.contactno1 }}</h6>

                    </div>

                </div>

                <div class="col-8" style="padding-top: 30px">
                    <div>
                        <h4>Who is {{ detail.name }}</h4>
                        {% for intro in cv.introductioncv2.all %}



                            <p>{{ intro.introcv2 }}</p>
                        {% endfor %}
                    </div>
                    <hr  style="background-color: #38b6ff; height: 10px">

                    <div>
                        <h4>Professional Experience </h4>
                        {% for exp in detail.experience.all %}

                            <h6>{{ exp.organization }} </h6>

                            <p>{{ exp.previousDesignation}} - {{ exp.startingDate }} to {{ exp.endingDate }}</p>

{#                            <h4>SUBJECT MATTER EXPERTISE EXPERIENCE </h4>#}
{#                            <h7>Sagar is one of the 47 Board Members on EC-Council Governance#}
{#                                Board For Ethical Hacking - IMEA Region. He is also one of the 34 Career#}
{#                                Mentors for Cybrary, Further Sagar is helping Udacity by Designing the#}
{#                                world's first NANO DEGREE in Information Security</h7>#}
                        {% endfor %}

                    </div>

                    <hr  style="background-color: #38b6ff; height: 10px">

                    <div>
                        <h4>PROFESSIONAL CERTIFICATIONS</h4>
                        {% for cer in cv.certificatecv2.all %}
                        <h6>{{ cer.certcv2 }} </h6>
                        {% endfor %}
                        <h7></h7>


                    </div>

                    <hr  style="background-color: #38b6ff; height: 10px">

                    <div>
                        <h4>Awards</h4>
                        {% for awd in cv.awardscv2.all %}
                        <h6>{{ awd.awcv2 }}</h6>
                        {% endfor %}

{#                        <h4>AIM - ARENA INTERNATIONAL MASTER</h4>#}
{#                        <h6>World Chess Federation - FIDE | Sepetember 2018 </h6>#}


                    </div>



                </div>
            </div>

        </div>


    </main>


{% endblock %}

dashboard/templates/dashboard/profile_view.html
{% extends 'basetemplate.html' %}
{% load static %}
{% block content %}


    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Profile Details</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                    <a href="{% url 'dashboard:updateinfo'  %}" class="btn btn-sm btn-outline-secondary"><i class="fas fa-plus"></i> Edit</a>
                    {#                    <a href="{% url 'employee:employeepic' id=id %}" class="btn btn-sm btn-outline-secondary"><i class="fas fa-plus"></i>  Add Picture</a>#}
                    <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#exampleModal" ><i class="fas fa-plus"></i> Update Picture</button>
                </div>
            </div>
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Picture</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form  class="form-group " action="{% url 'dashboard:employeepic' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <div class="modal-footer">
                            <input class="  btn btn-primary" type="submit" value="create">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="container-fluid " style=" text-align: center">
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-3 ">
                    <div class="card" >
                        <img  style="width: auto; height: auto " src="{{detail.profile_pic.url}}">
                        <div class="card-body">
                            <h5  name="fname">{{ detail.name }} {{ detail.fname }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-sm col-md" >
                    <div class="card">
                        <div class="card-header">
                            <h5  name="fname"> {{ detail.name }} {{ detail.fname }}</h5>
                        </div>
                        <div class="card-body">
{#                            <blockquote class="blockquote mb-0">#}
{#                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>#}
{#                            </blockquote>#}
                            <div class="row">
                                <div class="col3"><h5><label>Age : </label></h5></div>
                                <div class="col4" style="margin-left: 30px"><h5>{{ detail.age }}</h5></div>
                            </div>
                            <div class="row">
                                <div class="col3"><h5><label>Email: </label></h5></div>
                                <div class="col3" style="margin-left: 25px"><h5>{{ detail.email }}</h5></div>
                            </div>
                            <div class="row">
                                <div class="col3"><h5><label>Gender: </label></h5></div>
                                <div class="col3" style="margin-left: 12px"><h5>{{ detail.gender }}</h5></div>
                            </div>
{#                            <footer>#}
{#                                <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#exampleModal" ><i class="fas fa-plus"></i> Update Picture</button>#}
{#                            </footer>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <br>
            <br>
            <H2>Education</H2>
            <div class="table-responsive-lg" >
                <table class="table table-bordered table-striped">
                    <thead style="background-color: #10717F; color: white">
                    <tr>
                        <th>Institute</th>
                        <th>Board</th>
                        <th>Degree</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Result</th>
                        <th>Percentage</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for edu in detail.education.all %}
                        <tr>
                            <td>{{ edu.institute }}</td>
                            <td>{{ edu.board }}</td>
                            <td>{{ edu.degree }}</td>
                            <td>{{ edu.startingdate }}</td>
                            <td>{{ edu.endingdate }}</td>
                            <td>{{ edu.result }}</td>
                            <td>{{ edu.percentage }}%</td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>

            <H2>Experience</H2>
            <div class="table-responsive-lg">
                <table class="table table-bordered table-striped">
                    <thead style="background-color: #10717F; color: white">
                    <tr>
                        <th>Organization</th>
                        <th>Previous Designation</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Responsibilities</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for exp in detail.experience.all %}
                        <tr>
                            <td>{{ exp.organization }}</td>
                            <td>{{ exp.previousDesignation }}</td>
                            <td>{{ exp.startingDate }}</td>
                            <td>{{ exp.endingDate }}</td>
                            <td>{{ exp.responsibilities }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <h2>Skills</h2>
            <div class="table-responsive-lg">
                <table class="table table-striped table-striped">
                    <tbody>
                    {% for skl in detail.skills.all %}
                        <tr>
                        <td>{{ skl.skills }}</td>
                    {% endfor %}
                    </tbody>

                </table>
            </div>




        </div>
    </main>
    </div>
    </div>

{% endblock %}

dashboard/templates/dashboard/selectCV.html
{% extends 'basetemplate.html' %}
{% load static %}

{%block content  %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4" xmlns="http://www.w3.org/1999/html">



        {% if flag %}
        {% else %}
            <div class="alert alert-danger" role="alert" >
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5>Please complete your profile</h5>

            </div>
        {% endif %}

        <h1 style="color: #10717F">Choose Your CV Template</h1>

        <div class="row">
{#                    {% if flag %}#}
{#                    {% else %}#}
{#                        <div class="alert alert-dark" role="alert">#}
{#                            Please complete your profile</div>#}
{#                    {% endif %}#}
            <div class="col-2 " style="margin-right: 10px">
                <div class="card"  style="width: 10rem; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);margin-top: 15px;margin-left: 15px">
                    <a href="{% url 'dashboard:updateform1' %}"> <img  class="card-img-top" src="{% static 'fullblue cv.jpg' %}" alt="Card image cap"></a>
                </div>
            </div>


            <div class="col-2">
                <div class="card" style="width: 10rem;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);margin-top: 15px">
                    <a href="{% url 'dashboard:resumeform2' %}"> <img  class="card-img-top" src="{% static 'blackcv.jpg' %}" alt="Card image cap"></a>
                </div>
            </div>

        </div>
    </main>

{% endblock %}